# ML-10 — Content Action Playbook

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/133Haseeb/MLflyrankhaseeb/blob/main/work/notebooks/w07_action_playbook.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. Ranked actions + reason codes

*The queue: what to do first, and why, in words a human trusts.*

Ranked Actions + Reason Codes

The trained Random Forest model predicts whether a webpage is likely to need a content refresh. The predicted probabilities are used to rank webpages so that the SEO team can review the highest-priority pages first.

| Priority | Action | Reason Code |
|----------|----------------------|----------------------|
| High | Refresh Immediately | HIGH_REFRESH_SCORE |
| Medium | Review Content | POSSIBLE_DECLINE |
| Medium | Monitor Closely | MODERATE_RISK |
| Low | Monitor | LOW_RISK |
| Lowest | No Action | STABLE_PAGE |

The ranking helps prioritize pages for review. Final content decisions should always be made by a human reviewer.

## 2. Intended use and limits

*Who uses this, for what — and where it stops being valid.*

Intended Use

This model is designed to help SEO teams identify webpages that may require a content refresh based on historical search performance.

The model provides decision-support only and does not automatically update or publish content.

Intended Users

SEO Specialists

Content Managers

Content Writers

Limits

The model learns only from historical warehouse data.

It cannot understand content quality or writing style.

It cannot identify seasonal effects or business priorities.

It should not replace human review.

The model should be retrained when website behavior changes.

## 3. Human review + the no-go list

*What a person must check before acting. What should never be automated.*

Human Review

Before refreshing a webpage, a reviewer should check:

Whether the content is still accurate.

Whether traffic changes are seasonal.

Whether competitors have updated similar content.

Whether the page is still important for the business.

Whether technical SEO issues caused the decline.

No-Go List

These actions should never be automated:

Publishing new content

Deleting webpages

Editing legal or medical information

Changing pricing

Updating company policies

These decisions always require human approval.

## 4. Monitoring / retrain triggers

*What would tell you the recommendations went stale?*

Monitoring and Retraining

The model should be monitored regularly.

Retraining is recommended when:

Prediction performance decreases.

Large amounts of new content are added.

Search behavior changes significantly.

Search engine algorithms change.

New historical data becomes available.

Regular maintenance every 6–12 months.

## 5. Exports for the paper

*Write the queue (and any figures you want to reuse) to work/outputs/ — your paper builds on these files.*

In [1]:
%pip -q install duckdb huggingface_hub

In [2]:
from google.colab import userdata
import duckdb
import pandas as pd
import os

HF_TOKEN = userdata.get("HF_Token")

con = duckdb.connect()

con.execute(f"""
CREATE OR REPLACE SECRET hf
(TYPE huggingface, TOKEN '{HF_TOKEN}')
""")

REL = "hf://datasets/FlyRank/internship-warehouse"

TABLE = f"read_parquet('{REL}/fact_content_daily_performance/**/*.parquet')"

print("Connected Successfully!")

Connected Successfully!

In [3]:
features = con.sql("""

WITH page_features AS (

SELECT

client_hash_id,
content_hash_id,

AVG(gsc_impressions) AS avg_impressions,
AVG(gsc_clicks) AS avg_clicks,
AVG(gsc_avg_position) AS avg_position,

AVG(ga4_pageviews) AS avg_pageviews,
AVG(ga4_sessions) AS avg_sessions,
AVG(ga4_users) AS avg_users,

SUM(ai_chatgpt+ai_perplexity+ai_gemini+
    ai_copilot+ai_claude+ai_meta+ai_other) AS ai_traffic,

AVG(scroll_events) AS avg_scroll,

COUNT(*) AS days_observed,

CASE

WHEN AVG(gsc_impressions)>=100 THEN 1
ELSE 0

END AS needs_refresh

FROM read_parquet('hf://datasets/FlyRank/internship-warehouse/fact_content_daily_performance/**/*.parquet')

GROUP BY

client_hash_id,
content_hash_id

)

SELECT *

FROM page_features

""").df()

features.head()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,client_hash_id,content_hash_id,avg_impressions,avg_clicks,avg_position,avg_pageviews,avg_sessions,avg_users,ai_traffic,avg_scroll,days_observed,needs_refresh
0,client_9958f0a7ae1df715,content_3b70a18ea133b2bb,23.609615,0.098077,27.339604,0.000000,0.000000,0.000000,0.0,0.000000,520,0
1,client_9958f0a7ae1df715,content_c899aef92518c714,59.146154,0.221154,33.712361,0.107692,0.098077,0.090385,5.0,0.057692,520,0
2,client_9958f0a7ae1df715,content_c7c1d2e68d9d0964,11.569231,0.034615,35.538566,0.028846,0.028846,0.028846,0.0,0.003846,520,0
3,client_9958f0a7ae1df715,content_ae5e5fd6edff550f,27.850000,0.050000,16.941366,0.063462,0.063462,0.059615,0.0,0.015385,520,0
4,client_9958f0a7ae1df715,content_a64143f6e4a21ffe,791.925000,5.667308,14.952705,0.853846,0.811538,0.803846,0.0,0.401923,520,1

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

selected_features=[

"avg_impressions",
"avg_clicks",
"avg_position",
"avg_pageviews",
"avg_sessions",
"avg_users",
"ai_traffic",
"avg_scroll",
"days_observed"

]

X=features[selected_features]

y=features["needs_refresh"]

X_train,X_test,y_train,y_test=train_test_split(

X,
y,
test_size=0.20,
random_state=42,
stratify=y

)

model=RandomForestClassifier(

n_estimators=200,
random_state=42,
n_jobs=-1

)

model.fit(X_train,y_train)

RandomForestClassifier(n_estimators=200, n_jobs=-1, random_state=42)

In [5]:
features["refresh_probability"]=model.predict_proba(X)[:,1]
features["prediction"]=model.predict(X)

In [6]:
def action(prob):

    if prob>=0.90:
        return "Refresh Immediately"

    elif prob>=0.70:
        return "Review Content"

    elif prob>=0.50:
        return "Monitor Closely"

    elif prob>=0.30:
        return "Monitor"

    else:
        return "No Action"

In [7]:
def reason(prob):

    if prob>=0.90:
        return "HIGH_REFRESH_SCORE"

    elif prob>=0.70:
        return "POSSIBLE_DECLINE"

    elif prob>=0.50:
        return "MODERATE_RISK"

    elif prob>=0.30:
        return "LOW_RISK"

    else:
        return "STABLE_PAGE"

In [8]:
features["recommended_action"]=features["refresh_probability"].apply(action)

features["reason_code"]=features["refresh_probability"].apply(reason)

In [9]:
queue=features.sort_values(

"refresh_probability",
ascending=False

)

queue.head(20)

,client_hash_id,content_hash_id,avg_impressions,avg_clicks,avg_position,avg_pageviews,avg_sessions,avg_users,ai_traffic,avg_scroll,days_observed,needs_refresh,refresh_probability,prediction,recommended_action,reason_code
266642,client_e547b89c05043229,content_16827cede7dda2a2,134.908046,0.160920,6.819242,0.241379,0.210728,0.195402,0.0,0.034483,261,1,1.0,1,Refresh Immediately,HIGH_REFRESH_SCORE
229406,client_62f4a7e64f5e0096,content_bdd44c64dfe8e06d,388.879518,0.159639,5.668741,0.000000,0.000000,0.000000,0.0,0.000000,332,1,1.0,1,Refresh Immediately,HIGH_REFRESH_SCORE
25034,client_23a62021009f63c4,content_8b6382751f9b23d6,178.635714,0.439286,23.306158,1.485714,0.832143,0.807143,0.0,0.050000,280,1,1.0,1,Refresh Immediately,HIGH_REFRESH_SCORE
25036,client_23a62021009f63c4,content_f0cb68f63c745b06,172.892857,1.092857,6.964491,2.439286,1.307143,1.235714,0.0,0.100000,280,1,1.0,1,Refresh Immediately,HIGH_REFRESH_SCORE
229403,client_62f4a7e64f5e0096,content_fb9b2ea009b97c6a,263.346386,0.668675,4.712470,0.000000,0.000000,0.000000,0.0,0.000000,332,1,1.0,1,Refresh Immediately,HIGH_REFRESH_SCORE
229402,client_62f4a7e64f5e0096,content_2f6f693be4179822,144.259819,0.105740,7.951653,0.000000,0.000000,0.000000,0.0,0.000000,331,1,1.0,1,Refresh Immediately,HIGH_REFRESH_SCORE
229401,client_62f4a7e64f5e0096,content_f9ca2313187b46b7,357.223565,0.356495,5.559480,0.000000,0.000000,0.000000,0.0,0.000000,331,1,1.0,1,Refresh Immediately,HIGH_REFRESH_SCORE
149614,client_73cda7b4e4f265ea,content_1a567e21c229ca1d,340.803030,1.136364,5.491420,2.000000,1.617647,1.519608,0.0,0.068627,132,1,1.0,1,Refresh Immediately,HIGH_REFRESH_SCORE
132257,client_62f4a7e64f5e0096,content_e850689527cd6c83,196.941935,0.464516,4.520503,0.000000,0.000000,0.000000,0.0,0.000000,155,1,1.0,1,Refresh Immediately,HIGH_REFRESH_SCORE
375122,client_a80fca3f171ed1de,content_cf10f0882ebab4ab,253.634146,1.056911,3.864650,0.975000,0.891667,0.891667,3.0,0.125000,123,1,1.0,1,Refresh Immediately,HIGH_REFRESH_SCORE
25038,client_23a62021009f63c4,content_99cc4061cbe916a2,175.967857,0.439286,36.333224,6.685714,5.657143,5.721429,0.0,0.664286,280,1,1.0,1,Refresh Immediately,HIGH_REFRESH_SCORE
375120,client_a80fca3f171ed1de,content_df5c705dee1642b6,141.707317,0.601626,7.871842,0.541667,0.566667,0.558333,0.0,0.116667,123,1,1.0,1,Refresh Immediately,HIGH_REFRESH_SCORE
375119,client_a80fca3f171ed1de,content_7bbc06fb998c8b83,301.382114,0.056911,9.092516,0.058333,0.066667,0.066667,0.0,0.008333,123,1,1.0,1,Refresh Immediately,HIGH_REFRESH_SCORE
375118,client_a80fca3f171ed1de,content_ae941d65b87a8306,2301.666667,4.560976,5.283047,3.133333,2.841667,2.800000,0.0,0.333333,123,1,1.0,1,Refresh Immediately,HIGH_REFRESH_SCORE
266647,client_e547b89c05043229,content_6a7af5263f78ec10,266.862069,2.375479,6.293081,3.065134,2.478927,2.394636,0.0,0.176245,261,1,1.0,1,Refresh Immediately,HIGH_REFRESH_SCORE
25039,client_23a62021009f63c4,content_ef70a59024cea1ef,138.553571,1.346429,9.765411,3.285714,1.660714,1.578571,0.0,0.146429,280,1,1.0,1,Refresh Immediately,HIGH_REFRESH_SCORE
229400,client_62f4a7e64f5e0096,content_f0931763f2cb22bd,114.036145,0.262048,5.867191,0.000000,0.000000,0.000000,0.0,0.000000,332,1,1.0,1,Refresh Immediately,HIGH_REFRESH_SCORE
12305,client_62f4a7e64f5e0096,content_3af5019a9c1b0940,350.965909,2.250000,9.564878,0.000000,0.000000,0.000000,0.0,0.000000,352,1,1.0,1,Refresh Immediately,HIGH_REFRESH_SCORE
266633,client_e547b89c05043229,content_a4db6a77abb3ab2b,158.517241,0.218391,4.764422,0.367816,0.337165,0.310345,0.0,0.038314,261,1,1.0,1,Refresh Immediately,HIGH_REFRESH_SCORE
25022,client_23a62021009f63c4,content_7189af8eea4d63e9,170.946429,0.117857,16.102541,0.892857,0.642857,0.639286,6.0,0.050000,280,1,1.0,1,Refresh Immediately,HIGH_REFRESH_SCORE

In [10]:
os.makedirs("work/outputs",exist_ok=True)

queue.to_csv(

"work/outputs/final_action_playbook.csv",

index=False

)

print("Action Playbook exported successfully!")

queue.head(20)

Action Playbook exported successfully!

,client_hash_id,content_hash_id,avg_impressions,avg_clicks,avg_position,avg_pageviews,avg_sessions,avg_users,ai_traffic,avg_scroll,days_observed,needs_refresh,refresh_probability,prediction,recommended_action,reason_code
266642,client_e547b89c05043229,content_16827cede7dda2a2,134.908046,0.160920,6.819242,0.241379,0.210728,0.195402,0.0,0.034483,261,1,1.0,1,Refresh Immediately,HIGH_REFRESH_SCORE
229406,client_62f4a7e64f5e0096,content_bdd44c64dfe8e06d,388.879518,0.159639,5.668741,0.000000,0.000000,0.000000,0.0,0.000000,332,1,1.0,1,Refresh Immediately,HIGH_REFRESH_SCORE
25034,client_23a62021009f63c4,content_8b6382751f9b23d6,178.635714,0.439286,23.306158,1.485714,0.832143,0.807143,0.0,0.050000,280,1,1.0,1,Refresh Immediately,HIGH_REFRESH_SCORE
25036,client_23a62021009f63c4,content_f0cb68f63c745b06,172.892857,1.092857,6.964491,2.439286,1.307143,1.235714,0.0,0.100000,280,1,1.0,1,Refresh Immediately,HIGH_REFRESH_SCORE
229403,client_62f4a7e64f5e0096,content_fb9b2ea009b97c6a,263.346386,0.668675,4.712470,0.000000,0.000000,0.000000,0.0,0.000000,332,1,1.0,1,Refresh Immediately,HIGH_REFRESH_SCORE
229402,client_62f4a7e64f5e0096,content_2f6f693be4179822,144.259819,0.105740,7.951653,0.000000,0.000000,0.000000,0.0,0.000000,331,1,1.0,1,Refresh Immediately,HIGH_REFRESH_SCORE
229401,client_62f4a7e64f5e0096,content_f9ca2313187b46b7,357.223565,0.356495,5.559480,0.000000,0.000000,0.000000,0.0,0.000000,331,1,1.0,1,Refresh Immediately,HIGH_REFRESH_SCORE
149614,client_73cda7b4e4f265ea,content_1a567e21c229ca1d,340.803030,1.136364,5.491420,2.000000,1.617647,1.519608,0.0,0.068627,132,1,1.0,1,Refresh Immediately,HIGH_REFRESH_SCORE
132257,client_62f4a7e64f5e0096,content_e850689527cd6c83,196.941935,0.464516,4.520503,0.000000,0.000000,0.000000,0.0,0.000000,155,1,1.0,1,Refresh Immediately,HIGH_REFRESH_SCORE
375122,client_a80fca3f171ed1de,content_cf10f0882ebab4ab,253.634146,1.056911,3.864650,0.975000,0.891667,0.891667,3.0,0.125000,123,1,1.0,1,Refresh Immediately,HIGH_REFRESH_SCORE
25038,client_23a62021009f63c4,content_99cc4061cbe916a2,175.967857,0.439286,36.333224,6.685714,5.657143,5.721429,0.0,0.664286,280,1,1.0,1,Refresh Immediately,HIGH_REFRESH_SCORE
375120,client_a80fca3f171ed1de,content_df5c705dee1642b6,141.707317,0.601626,7.871842,0.541667,0.566667,0.558333,0.0,0.116667,123,1,1.0,1,Refresh Immediately,HIGH_REFRESH_SCORE
375119,client_a80fca3f171ed1de,content_7bbc06fb998c8b83,301.382114,0.056911,9.092516,0.058333,0.066667,0.066667,0.0,0.008333,123,1,1.0,1,Refresh Immediately,HIGH_REFRESH_SCORE
375118,client_a80fca3f171ed1de,content_ae941d65b87a8306,2301.666667,4.560976,5.283047,3.133333,2.841667,2.800000,0.0,0.333333,123,1,1.0,1,Refresh Immediately,HIGH_REFRESH_SCORE
266647,client_e547b89c05043229,content_6a7af5263f78ec10,266.862069,2.375479,6.293081,3.065134,2.478927,2.394636,0.0,0.176245,261,1,1.0,1,Refresh Immediately,HIGH_REFRESH_SCORE
25039,client_23a62021009f63c4,content_ef70a59024cea1ef,138.553571,1.346429,9.765411,3.285714,1.660714,1.578571,0.0,0.146429,280,1,1.0,1,Refresh Immediately,HIGH_REFRESH_SCORE
229400,client_62f4a7e64f5e0096,content_f0931763f2cb22bd,114.036145,0.262048,5.867191,0.000000,0.000000,0.000000,0.0,0.000000,332,1,1.0,1,Refresh Immediately,HIGH_REFRESH_SCORE
12305,client_62f4a7e64f5e0096,content_3af5019a9c1b0940,350.965909,2.250000,9.564878,0.000000,0.000000,0.000000,0.0,0.000000,352,1,1.0,1,Refresh Immediately,HIGH_REFRESH_SCORE
266633,client_e547b89c05043229,content_a4db6a77abb3ab2b,158.517241,0.218391,4.764422,0.367816,0.337165,0.310345,0.0,0.038314,261,1,1.0,1,Refresh Immediately,HIGH_REFRESH_SCORE
25022,client_23a62021009f63c4,content_7189af8eea4d63e9,170.946429,0.117857,16.102541,0.892857,0.642857,0.639286,6.0,0.050000,280,1,1.0,1,Refresh Immediately,HIGH_REFRESH_SCORE

## Self-check

Before you submit, confirm each line honestly:

- [checked ] Every section above is filled — markdown thinking AND the code that backs it
- [checked  ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [checked  ] No client names, URLs, or private queries anywhere
- [checked  ] My claims use careful words: observed, measured, directional, decision-support
- [checked  ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.